version: '3'

services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: dyaonly/green:nest
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mariadb
    expose:
      - 3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=nest
      - MARIADB_USER=nestuser
      - MARIADB_PASSWORD=nestpassword
    volumes:
      - ./data/db:/var/lib/mysql