name: EKS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      ecr_repository: ${{ steps.set_vars.outputs.ecr_repository }}
      image_tag: ${{ steps.set_vars.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set_vars
        run: |
          echo "::set-output name=ecr_repository::public.ecr.aws/l9d5m0q6/k8s-nest"
          echo "::set-output name=image_tag::latest"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  build:
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
      - name: Build, tag, and push image to Amazon ECR
        run: |
          cd /
          docker build -t ${{ needs.prebuild.outputs.ecr_repository }}:${{ needs.prebuild.outputs.image_tag }} --push .
        working-directory: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.K8S_CLUSTER_NAME }}
          kubectl apply -f k8s/.
